apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
       - name: aws-registry-secret
      containers:
      - name: $APP_NAME
        image: gbaderobusola/busola:$IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
